import { CircleAlert, MessageSquareText } from "lucide-react";
import Link from "next/link";
import type { UserRole } from "@/db/types";
import { Badge } from "@/components/ui/badge";
import type { DeveloperQuestionListItemDto } from "../queries";
export function DeveloperQuestionList({ role, items }: { role: UserRole; items: readonly DeveloperQuestionListItemDto[] }) {
  const sorted = [...items].sort((a, b) => Number(role === "CUSTOMER" ? b.attentionStatus === "WAITING_CUSTOMER" : b.attentionStatus === "WAITING_DEVELOPER") - Number(role === "CUSTOMER" ? a.attentionStatus === "WAITING_CUSTOMER" : a.attentionStatus === "WAITING_DEVELOPER") || +new Date(b.updatedAt) - +new Date(a.updatedAt));
  if (!sorted.length) return null;
  return <section className="question-list" aria-labelledby="developer-questions-heading"><h2 id="developer-questions-heading"><MessageSquareText size={18} />开发者提问</h2><div className="request-table-wrap"><table className="request-table"><thead><tr><th>编号与内容</th><th>项目</th><th>发起人</th><th>状态</th><th>更新时间</th></tr></thead><tbody>{sorted.map((q) => { const attention = role === "CUSTOMER" ? q.attentionStatus === "WAITING_CUSTOMER" : q.attentionStatus === "WAITING_DEVELOPER"; return <tr key={q.id} data-testid={`question-row-${q.questionNumber}`} data-attention={attention ? role === "CUSTOMER" ? "question-customer" : "question-developer" : undefined}><td className="request-table__primary" data-label="开发者提问"><div className="request-table__number-line"><Link href={`/questions/${q.questionNumber}`}>{q.questionNumber}</Link><Badge tone="info">开发者提问</Badge>{attention ? <span className="request-attention"><CircleAlert size={14} />{role === "CUSTOMER" ? "待您回复" : "客户已回复"}</span> : null}</div><Link href={`/questions/${q.questionNumber}`} className="request-table__summary">{q.summary}</Link></td><td data-label="项目">{q.project.name}</td><td data-label="发起人">{q.createdBy.displayName}</td><td data-label="状态">{q.attentionStatus === "WAITING_CUSTOMER" ? "待客户回复" : q.attentionStatus === "WAITING_DEVELOPER" ? "待开发者查看" : "已查看"}</td><td data-label="更新">{new Intl.DateTimeFormat("zh-CN", { month: "2-digit", day: "2-digit", hour: "2-digit", minute: "2-digit" }).format(new Date(q.updatedAt))}</td></tr>; })}</tbody></table></div></section>;
}
